#Roost XP Ratio
Ratio = 0.1
#Enable Crafting Grid for Guidebook
Enabled = true
#Roost Processing Speed in Seconds
"Roost Speed" = 20
#Breeder Processing Speed in Seconds
"Breeder Speed" = 20
#Trainer Processing Speed in Seconds
"Trainer Speed" = 100000
#Soul Breeder Processing Speed in Seconds
"Soul Breeder Speed" = 30
#Soul Extractor Processing Speed in Seconds
"Soul Extractor Speed" = 20
#Set Max level for Tier 1 Chicken
"Max level Tier 1" = 60
#Set Max level for Tier 2 Chicken
"Max level Tier 2" = 60
#Set Max level for Tier 3 Chicken
"Max level Tier 3" = 60
#Set Max level for Tier 4 Chicken
"Max level Tier 4" = 60
#Set Max level for Tier 5 Chicken
"Max level Tier 5" = 60
#Set Max level for Tier 6 Chicken
"Max level Tier 6" = 60
#Set Max level for Tier 7 Chicken
"Max level Tier 7" = 60
#Set Max level for Tier 8 Chicken
"Max level Tier 8" = 60
#Set Max level for Tier 9 Chicken
"Max level Tier 9" = 60
#Set required XP for Levelup for Tier 1 Chicken
"Required XP Tier 1" = 5000
#Set required XP for Levelup for Tier 2 Chicken
"Required XP Tier 2" = 10000
#Set required XP for Levelup for Tier 3 Chicken
"Required XP Tier 3" = 20000
#Set required XP for Levelup for Tier 4 Chicken
"Required XP Tier 4" = 30000
#Set required XP for Levelup for Tier 5 Chicken
"Required XP Tier 5" = 40000
#Set required XP for Levelup for Tier 6 Chicken
"Required XP Tier 6" = 50000
#Set required XP for Levelup for Tier 7 Chicken
"Required XP Tier 7" = 60000
#Set required XP for Levelup for Tier 8 Chicken
"Required XP Tier 8" = 70000
#Set required XP for Levelup for Tier 9 Chicken
"Required XP Tier 9" = 80000
#Set XP Amount for Vanilla Seeds
XP = 10
#Set XP Amount for Seed Tier 1
"Seed Tier 1" = 1000
#Set XP Amount for Seed Tier 2
"Seed Tier 2" = 1250
#Set XP Amount for Seed Tier 3
"Seed Tier 3" = 1750
#Set XP Amount for Seed Tier 4
"Seed Tier 4" = 2500
#Set XP Amount for Seed Tier 5
"Seed Tier 5" = 3500
#Set XP Amount for Seed Tier 6
"Seed Tier 6" = 4750
#Set XP Amount for Seed Tier 7
"Seed Tier 7" = 6250
#Set XP Amount for Seed Tier 8
"Seed Tier 8" = 8000
#Set XP Amount for Seed Tier 9
"Seed Tier 9" = 10000

