comment1 = "Defines the Roost Production Speed in Seconds:"
roostspeed = 20
comment12 = "Defines the Level split for output in roost:"
leveloutputsplit = 2.0
comment2 = "Defines the Breeding Speed in Seconds:"
breederspeed = 20
comment3 = "Defines the Training Speed in Seconds:"
trainerspeed = 100000
comment4 = "Defines the Soul Extraction Speed in Seconds:"
soulextractspeed = 20
comment5 = "Defines the Soul Breeding Speed in Seconds:"
soulbreedspeed = 30
comment6 = "Defines the passive XP gained while Breeding or inside the Roost in Ratio like 0.1f = 10"
passivexp = 1.0
comment7 = "Defines the XP Amount per Seed Tier:"
seeds_tier_1 = 100
seeds_tier_2 = 125
seeds_tier_3 = 175
seeds_tier_4 = 250
seeds_tier_5 = 350
seeds_tier_6 = 475
seeds_tier_7 = 625
seeds_tier_8 = 800
seeds_tier_9 = 1000
comment8 = "Defines the XP required for a Levelup per Tier:"
xp_tier_1 = 5000
xp_tier_2 = 10000
xp_tier_3 = 20000
xp_tier_4 = 30000
xp_tier_5 = 40000
xp_tier_6 = 50000
xp_tier_7 = 60000
xp_tier_8 = 70000
xp_tier_9 = 80000
comment9 = "Defines the max Level per Tier:"
level_tier_1 = 60
level_tier_2 = 60
level_tier_3 = 60
level_tier_4 = 60
level_tier_5 = 60
level_tier_6 = 60
level_tier_7 = 60
level_tier_8 = 60
level_tier_9 = 60
comment10 = "Enable Breeder Crafting in both ways, this means it dont matter if u put the Chicken right or left."
enableboth = true
comment11 = "Change the Collectors max collecting Range:"
collector_maxrange = 30
comment13 = "Change the Feeder max feeding Range:"
feeder_maxrange = 30

