
[general]
	#Text color in hex code format
	text_color = "FFFFFF"
	#Show entity name
	show_entity_name = true
	#Disables the rendering of the vanilla name tag
	disable_name_tag = false
	#Maximum distance in blocks at which health bars should render
	max_distance = 24
	#Maximum distance in blocks at which health bars should render without line of sight
	max_distance_without_line_of_sight = 8
	#Whether health bars should render when the HUD is disabled with F1
	render_without_gui = false
	#How far above the mob the health bars should render
	height_above_mob = 0.6
	#Whether the gray background plate should be drawn
	draw_background = true
	#Amount of extra padding space around the background plate
	background_padding = 2
	#How tall the background plate should be
	background_height = 6
	#How tall the health bar should be
	health_bar_height = 4
	#How wide the health bar should be. If the entity has a long name, the bar will increase in size to match it.
	plate_size = 25
	#plateSize but for bosses
	plate_size_boss = 50
	#Show mob attributes such as arthropod or undead
	show_attributes = true
	#Show armor points
	show_armor = true
	#Group 5 iron icons into 1 diamond icon
	group_armor = true
	#Color health bar by mob type instead of health percentage
	color_health_bar_by_type = false
	#Height of the text on the health bar
	hp_text_height = 14
	#Whether the maximum health of the mob should be shown
	show_max_hp = true
	#Whether the current health of the mob should be shown
	show_current_hp = true
	#Whether the percentage health of the mob should be shown
	show_hp_percentage = true
	#Whether bars on passive mobs should be shown
	show_on_passive = true
	#Whether bars on hostile mobs should be shown (does not include bosses)
	show_on_hostile = true
	#Whether bars on players should be shown
	display_on_players = true
	#Whether bars on bosses should be shown
	display_on_bosses = true
	#Only show bars for mobs you are targeting
	only_health_bar_for_target = false
	#Show bars for mobs that are at full health
	show_entity_full_health = true
	#Show extra debug info on the bar when F3 is enabled
	show_debug_with_f3 = true
	#If this is enabled and the "disableNameTag" option is true, the vanilla nametag is only hidden if the mob has a Neat healthbar rendered
	disable_name_tag_if_healthbar = true
	#Offsets the healtbar icons on the x axis
	icon_offset_x = 0.0
	#Offsets the healtbar icons on the y axis
	icon_offset_y = 0.0
	#This value changes the decimal format of the HP. Only change this value if you are familiar with how the decimal format works!
	decimal_format = "#.##"
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	blacklist = ["polly_pets:dog", "polly_pets:chocolate_ferret", "polly_pets:sable_ferret", "polly_pets:kitty", "polly_pets:british_shorthair", "polly_pets:bombay", "polly_pets:ferret", "polly_pets:khao_manee", "polly_pets:calico", "alexsmobs:crow", "naturalist:cardinal", "naturalist:finch", "polly_pets:shihtzu", "polly_pets:bulldog", "polly_pets:golden_retriever", "polly_pets:jack_russell_terrier", "polly_pets:tibetan_mastiff", "polly_pets:poodle", "polly_pets:husky", "polly_pets:labrador", "polly_pets:cerberus", "polly_pets:borzoi", "polly_pets:bull_terrier", "polly_pets:leopard_gecko", "polly_pets:french_bulldog", "polly_pets:german_shepherd", "polly_pets:old_english_sheepdog", "polly_pets:pomeranian", "polly_pets:pug", "polly_pets:beagle", "polly_pets:st_bernard", "polly_pets:bernese_mountain_dog", "polly_pets:corgi", "polly_pets:dachshund", "polly_pets:dalmatian", "naturalist:canary", "naturalist:sparrow", "minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "alexsmobs:blobfish", "alexsmobs:devils_hole_pupfish", "alexsmobs:catfish", "alexsmobs:flying_fish", "crittersandcompanions:koi_fish", "naturalist:catfish", "untamedwilds:sunfish", "untamedwilds:ocean_sunfish", "untamedwilds:football_fish", "untamedwilds:triggerfish", "untamedwilds:catfish", "untamedwilds:spadefish", "untamedwilds:sawfish", "naturalist:bass", "untamedwilds:giant_salamander", "naturalist:robin", "duckling:duck", "alexsmobs:fly", "cataclysm:lionfish", "untamedwilds:trevally", "untamedwilds:arowana", "untamedwilds:newt", "untamedwilds:king_crab", "naturalist:butterfly", "naturalist:snail", "alexsmobs:lobster", "alexsmobs:stradpole", "alexsmobs:platypus", "alexsmobs:frilled_shark", "alexsmobs:mimic_octopus", "alexsmobs:terrapin", "alexsmobs:comb_jelly", "alexsmobs:cosmic_cod", "alexsmobs:mudskipper", "alexsmobs:triops", "quark:crab", "crittersandcompanions:sea_bunny", "crittersandcompanions:dumbo_octopus", "minecraft:tadpole", "minecraft:axolotl", "alexsmobs:hummingbird", "twilightforest:tiny_bird", "ylf_mod:ylf", "capybaramod:capybara", "minecraft:squid", "minecraft:guardian", "crittersandcompanions:otter", "untamedwilds:tortoise", "untamedwilds:snake", "alexsmobs:rattlesnake", "naturalist:snake", "naturalist:coral_snake", "naturalist:rattlesnake", "polly_pets:green_snake", "naturalist:tortoise", "alexsmobs:blue_jay", "naturalist:bluejay", "crittersandcompanions:ferret", "polly_pets:hamster", "polly_pets:orange_hamster", "crittersandcompanions:dragonfly", "crittersandcompanions:jumping_spider", "crittersandcompanions:leaf_insect", "crittersandcompanions:shima_enaga", "twilightforest:raven", "twilightforest:dwarf_rabbit", "twilightforest:helmet_crab", "twilightforest:mosquito_swarm", "twilightforest:squirrel", "ars_nouveau:drygmy", "ars_nouveau:starbuncle", "ars_nouveau:whirlisprig", "minecraft:bee", "minecraft:endermite", "minecraft:silverfish", "alexsmobs:banana_slug", "autumnity:snail", "naturalist:lizard", "untamedwilds:lizard", "naturalist:firefly", "alexsmobs:sugar_glider"]

