
[general]
	"Max Distance" = 24
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 0.6
	"Draw Background" = true
	"Background Padding" = 2
	"Background Height" = 6
	"Health Bar Height" = 4
	"Plate Size" = 25
	"Plate Size (Boss)" = 50
	"Show Attributes" = true
	"Show Armor" = true
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = false
	"HP Text Height" = 14
	"Show Max HP" = true
	"Show Current HP" = true
	"Show HP Percentage" = true
	"Display on Players" = true
	"Display on Bosses" = true
	"Only show the health bar for the entity looked at" = false
	"Show entities with full health" = true
	"Show Debug Info with F3" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["polly_pets:dog", "polly_pets:chocolate_ferret", "polly_pets:sable_ferret", "polly_pets:kitty", "polly_pets:british_shorthair", "polly_pets:bombay", "polly_pets:ferret", "polly_pets:khao_manee", "polly_pets:calico", "alexsmobs:crow", "naturalist:cardinal", "naturalist:finch", "polly_pets:shihtzu", "polly_pets:bulldog", "polly_pets:golden_retriever", "polly_pets:jack_russell_terrier", "polly_pets:tibetan_mastiff", "polly_pets:poodle", "polly_pets:husky", "polly_pets:labrador", "polly_pets:cerberus", "polly_pets:borzoi", "polly_pets:bull_terrier", "polly_pets:leopard_gecko", "polly_pets:french_bulldog", "polly_pets:german_shepherd", "polly_pets:old_english_sheepdog", "polly_pets:pomeranian", "polly_pets:pug", "polly_pets:beagle", "polly_pets:st_bernard", "polly_pets:bernese_mountain_dog", "polly_pets:corgi", "polly_pets:dachshund", "polly_pets:dalmatian", "naturalist:canary", "naturalist:sparrow", "minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "alexsmobs:blobfish", "alexsmobs:devils_hole_pupfish", "alexsmobs:catfish", "alexsmobs:flying_fish", "crittersandcompanions:koi_fish", "naturalist:catfish", "untamedwilds:sunfish", "untamedwilds:ocean_sunfish", "untamedwilds:football_fish", "untamedwilds:triggerfish", "untamedwilds:catfish", "untamedwilds:spadefish", "untamedwilds:sawfish", "naturalist:bass", "untamedwilds:giant_salamander", "naturalist:robin", "duckling:duck", "alexsmobs:fly", "cataclysm:lionfish", "untamedwilds:trevally", "untamedwilds:arowana", "untamedwilds:newt", "untamedwilds:king_crab", "naturalist:butterfly", "naturalist:snail", "alexsmobs:lobster", "alexsmobs:stradpole", "alexsmobs:platypus", "alexsmobs:frilled_shark", "alexsmobs:mimic_octopus", "alexsmobs:terrapin", "alexsmobs:comb_jelly", "alexsmobs:cosmic_cod", "alexsmobs:mudskipper", "alexsmobs:triops", "quark:crab", "crittersandcompanions:sea_bunny", "crittersandcompanions:dumbo_octopus", "minecraft:tadpole", "minecraft:axolotl", "alexsmobs:hummingbird", "twilightforest:tiny_bird", "ylf_mod:ylf", "capybaramod:capybara", "minecraft:squid", "minecraft:guardian", "crittersandcompanions:otter", "untamedwilds:tortoise", "untamedwilds:snake", "alexsmobs:rattlesnake", "naturalist:snake", "naturalist:coral_snake", "naturalist:rattlesnake", "polly_pets:green_snake", "naturalist:tortoise", "alexsmobs:blue_jay", "naturalist:bluejay", "crittersandcompanions:ferret", "polly_pets:hamster", "polly_pets:orange_hamster", "crittersandcompanions:dragonfly", "crittersandcompanions:jumping_spider", "crittersandcompanions:leaf_insect", "crittersandcompanions:shima_enaga", "twilightforest:raven", "twilightforest:dwarf_rabbit", "twilightforest:helmet_crab", "twilightforest:mosquito_swarm", "twilightforest:squirrel", "ars_nouveau:drygmy", "ars_nouveau:starbuncle", "ars_nouveau:whirlisprig", "minecraft:bee", "minecraft:endermite", "minecraft:silverfish", "alexsmobs:banana_slug", "autumnity:snail", "naturalist:lizard", "untamedwilds:lizard", "naturalist:firefly", "alexsmobs:sugar_glider"]
	"Max Distance Without Line of Sight" = 8
	#Text color in hex code format
	text_color = "FFFFFF"
	#Whether bars on passive mobs should be shown
	showOnPassive = true
	#Whether bars on hostile mobs should be shown (does not include bosses)
	showOnHostile = true
	show_entity_name = true
	#Disables the rendering of the vanilla name tag
	disable_name_tag = false

